fix legacy bug  and update to depend anki 2.1.36
ankicommunity/anki-sync-server pull request #36
Opened 2020-10-27 03:55 UTC by cecini

* update ankisyncd _homepage
* enable V2 scheduler 
* fix the remove deck call fail,change intruduced after 3.1.28 f592672fa
* once client items in graves have been remove in the server,need update graves usn

* update dependency anki and ankirspy to 2.1.36(06292a45f304fc3c9ea2ef09789b090b2e368016),
    with 
    patch  align rslib get_subnode impl with anki pythonapi find_deck_in_tree #805  
    https://github.com/ankitects/anki/pull/805
    once not apply the patch , the nestdeck sync will fail,lead to recheck database errro on desktop.
    So you can only use the nonnestdeck without the patch.

Note: Look like the bug intruduced after the 2.1.28, so the update dependency is not related with the bug fixed.

Now test to be working with anki 2.1.36 desktop , AnkiDroid 2.13.5.

2020-10-28 17:48 UTC, inevity commented
* Once client items in graves have been removed in the server,need update graves usn to current max usn.
The bug look like that set server=True is not working, initially use the self.col.db.execute("update graves set usn=? where usn=-1",   self.maxUsn) to fix ,now use the chang the ankisyncserve boostrap way to open collection as server mode(to pass info to rsbackend), so the card/note/deck remvoe will add grave entry to the grave table and set usn as maxusn.

2020-10-30 03:14 UTC, cecini commented
Once client items in graves have been removed in the server, need update graves usn to current max usn.
The bug look like that set server=True is not working, initially use the self.col.db.execute("update graves set usn=? where usn=-1", self.maxUsn) to fix ,now use the chang the ankisyncserve boostrap way to open collection as server mode(to pass info to rsbackend), so the card/note/deck remove will add grave entry to the grave table and set usn as maxusn(in remove impl of rsbackend)

2020-11-01 19:28 UTC, VikashKothary requested changes
Thank you for your contribution.

I still need to check your legacy bug fix but I've left some comments in the meantime. Is there more information about this legacy bug you're trying to solve? I assume it's the v2 schedular i.e. https://github.com/ankicommunity/anki-sync-server/issues/31?

Also try and keep minor changes like the homepage change and version bumps as separate PRs because they'll get merged easier and quicker.

2020-11-01 19:28 UTC, VikashKothary commented on src/ankisyncd/__init__.py
> +_homepage = "https://github.com/ankicommunity/anki-sync-server.git"
Nice!

2020-11-01 19:28 UTC, VikashKothary commented on src/requirements.txt
> +anki==2.1.36
Nice. But this requirements.txt is a generated file and the version change should actually be done in the pyproject.toml. I've opened a new issue related to this here: https://github.com/ankicommunity/anki-sync-server/issues/41.

2020-11-01 19:28 UTC, VikashKothary commented on src/ankisyncd/sync_app.py
>          if offset is not None:
This if-statement is redundant if we're no longer raising an exception. It should either be removed or a log message should be included.

2020-11-02 03:02 UTC, liu-hz commented
Do we need to adjust the version of anki when we upgrade it requirements.txt Then update the PIP tool library? Thank you very much for your continuous update and maintenance of anki upgrade. Thank you very much

2020-11-03 10:30 UTC, cecini commented
@VikashKothary  just split to small prs.
For your clarity: 
    * update ankisyncd _homepage #45
    * enable V2 scheduler #46 
    * update dependency anki and ankirspy #47 
    * fix the remove deck lead server crash issue #28,change intruduced after 3.1.28 f592672fa #48 
    * fix: once client items in graves have been remove in the server,need update graves usn as maxusn #49 
    * fix client add then delete item then sync issue, deck/card/note must not been synced after client add #51 
    * ensure mediadir exsit in the case full sync ok after delete server collection dir #50

2020-12-05 17:47 UTC, closed without merging